### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by thatguy14** [Darakah/obsidian-timelines#13]
Hello - I am trying to install the plugin using obsidian and every time I try to install it immediately fails. The developer console is giving this:

Failed to load resource: the server github.com/Darakah/o...3.0/manifest.json:1 responded with a status of 404 ()

Someone in discord mentioned they were still able to update - I am trying to do a fresh install.

Thanks for the help

**Comment by Darakah** [comment]
@thatguy14 , try now it should work. what happened is that I pushed a new version yesterday `0.3.0` but didn't add a release for it because I want it to stress test more to make sure everything is good. And for some reason obsidian picked up on it even though there was no release and tried to install it. 

Sorry about that!

**Comment by thatguy14** [comment]
Thanks!

**Comment by thatguy14** [comment]
Sorry I went to go and test it and the steps you outline don't seem to work and wondering if related to this. Specifically when I follow the steps at the selection of test;me and then pressing control+p and searching for timeline, it doesn't appear even though it is enabled:

![timeline-ex](https://user-images.githubusercontent.com/25937625/113506228-90b9a400-9511-11eb-87ef-b2fd47928c12.png)

Hopefully I haven't missed something obvious
