### ISSUE TITLE
Very difficult to understand how to install it and begin to use

### ISSUE THREAD

**Issue by myownstandard** [Darakah/obsidian-timelines#2]
Could you make some video or gif tutorial with basics of using the plugin? I tried to follow your manual but totally failed. Very cool plugin but quite impossible for not experienced users to start use plugin..

**Comment by Darakah** [comment]
Hello, 

Can you specify what is unclear if possible? 

1. `how to install` : did you install from the Obsidian `Community Plugins` tab? (You only have to click install then the activate button from the same tab. Are you trying to install manually?? If so, you just have to download the three files from the latest release tab ... but given that you say you are not experienced I don't see why you should try a manual install.

2. `begin to use`? 

a) Create an empty note
b) Write this on the first line of the note (Not sure if you know what YAML is?)
```
---
tags: [timeline, test, me, now]
---
``` 
(exactly like this copy paste along with the things ---)

c) add the timeline info to this note by copy pasting this line (in the same note)

```
<span class='ob-timelines' data-date='1444-10-00-00' data-title='TITLE' data-img = 'https://i.pinimg.com/564x/03/b2/12/03b2128a911d9a8168189201b358a8d0.jpg'> D E S C R  </span>
```

d) write this in the note on a new line (copy paste this line)
```
test;me
```

e) SELECT `test;me` that you just wrote 

<img width="780" alt="Screen Shot 2021-02-10 at 10 36 34 PM" src="https://user-images.githubusercontent.com/29651407/107575687-6f62c880-6bf0-11eb-8961-7d4d6cbde48f.png">

(text selection: https://static.javatpoint.com/msword/images/how-to-select-text-in-ms-word1.png)

f) open the obsidian commands by clicking `command+P` if you are on Mac or `control+P` if you are on windows. 

<img width="982" alt="Screen Shot 2021-02-10 at 10 39 31 PM" src="https://user-images.githubusercontent.com/29651407/107575985-d8e2d700-6bf0-11eb-8dd4-042262320331.png">

search for `time` the first command you should see is called `create timeline`

this will replace the text you selected i.e. `test;me` with the html text for the timeline for these chosen tags. 

<img width="952" alt="Screen Shot 2021-02-10 at 10 40 06 PM" src="https://user-images.githubusercontent.com/29651407/107576044-ee580100-6bf0-11eb-97e4-4801f516fa4e.png">

g) click `command + E` if on mac or `control + E` if on windows to change to preview mode.

.... watch the nice single panel timeline ....

h) repeat the process for all other notes that you wish to add to the timeline 

-----

At which step do you get stuck / doesn't work???

**Comment by myownstandard** [comment]
Thanks for respond! Now it works like a charm! With your step by step guide i have understood how to make plugin work! The thing is that when i see pictures that you send me in instruction it is much easier to understand the whole process. https://github.com/Darakah/obsidian-timelines was not clear for me.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Darakah** [comment]
Glad it works!
Consider giving the Github Project a `Star` if you liked the plugin.

**Comment by emory** [comment]
When I `Create Timeline` it replaces my `keyword1;keyword2;keyword3` with `<div class="timeline"></div>` and I don't know what I could be doing wrong there.

**Comment by Darakah** [comment]
Hello,
this happens when there is no note to present which can be caused by one of the following reasons:

- There is no note having **_ALL of the tags searched_** for in the **_YAML_** (its important to note that the tags must be in the YAML and not simple normal note within the note (they are recorded separately by obsidian). This below must be in at least 1 note.

```
---
tags: [timeline, keyword1, keyword2, keyword3] 
---
```

- No note with all the tag searches has a `timeline` tag (or the modified tag you set in options) in its YAML (same as above this tag has to be in the YAML)

- No note with all the tag searches and the timeline tag `has a proper info block` 

- All notes found have bad dates (as a note with a bad date is ignored). 

@emory Can you please post an example note if the above doesn't help.

**Comment by Magicrevette** [comment]
Hello. I trie the timeline plugin here, and I don't understand the link between the timeline and the tags. I created a timeline note, in wich I wrote tags : [test]. In another note, i worte #test. Then I followed your tutorial and managed to create a timeline. It displays ok. But none of timeline-card seem linked to my #test. Neither in title nor in description.

Then I tried to write [[notename]] in the title and in the description to see if I could link a timeline-card to a note by this way, and I couldn't. But the plugin doesn't seem to work this way.

What am I doing wrong ? What is the "link" between tags and timeline-card ?

**Comment by Darakah** [comment]
What happens when you `click` on the title of a  timeline-card? It is supposed to jump you to the note of origin of that timeline-card. (If you just place the cursor over the title and you have activated the option to preview links you can also see a preview). 

<img width="933" alt="Screen Shot 2021-02-24 at 12 50 06 PM" src="https://user-images.githubusercontent.com/29651407/108996568-d5465a00-769e-11eb-9880-caa45f75c03b.png">

-> In regards to the period of time, what I do is create an MOC of that period (a note containing a link to all events from that period) and then add only this note to the timeline. Not sure how else to `represent` a period in the current format. I welcome any ideas.

**Comment by Magicrevette** [comment]
I don't have this behavior.

This is my note where I have a tag #test : 
![image](https://user-images.githubusercontent.com/34645582/109007918-f746d900-76ac-11eb-84c8-fca360b712fe.png)

Here is my timeline note : 
![image](https://user-images.githubusercontent.com/34645582/109008146-442aaf80-76ad-11eb-94f2-f6286e808a69.png)

And after I create a timeline with ctrl+P : 
![image](https://user-images.githubusercontent.com/34645582/109008300-74724e00-76ad-11eb-8dd1-c222bde82506.png)

Here is the result in Preview Mode : 
![image](https://user-images.githubusercontent.com/34645582/109008415-979cfd80-76ad-11eb-8e20-b556de7b720a.png)

Nothing appears when I hoover the title, nor when I click on it.

->For the period representation, I don't know how you could do it. It's more difficult here because it's vertical. Maybe the left of the timeline could be used for ponctual events, and the right fort periods of time ? Like this : 
![image](https://user-images.githubusercontent.com/34645582/109009064-5b1dd180-76ae-11eb-80b4-b0feaf8154c5.png)

The ponctual cards could have a different color than the period cards, to distinguish them. The ponctual cards could also have a pointer, like an arrow, to target when they occur in the timeline, while period cards could have "brackets" (a doted line pointing at the period start and another pointing at the period end). The difficul part here would be to make period cards that overlap eachother still be readable. To do so, the right side of the timeline (where the period events are in this example) could be split in numerous columns when there are overlapping period events, so each of them could be in a separete column...

Maybe have you already thought about all this, but the developping part is difficult or long. I don't know, I'm not a developper. Thank you for your plugin and for the time you're according to the community :)

**Comment by Darakah** [comment]
@Magicrevette 

### **_Regarding the jumping behavior:_**
----

**_Problem:_** It seems you misunderstood how it works (most likely because in the above example I used the same note as a timeline note AND the note where I want to put a timeline). I will explain clearly below how it works and then highlight the problem with your note, please let me know if it remains unclear:

- There is `no single timeline`: a timeline can be inserted in ANY NOTE and AS MANY TIMES AS YOU WANT. It can be an empty note (not even metadata or tags).
- The `YAML metadata` + `span containing the time info` are supposed to be in your `Repository` note not in the note where you want to insert the timeline. What is happening here is that you are displaying the `timeline` note as a timeline card (your other note is ignored for many reasons - please read the full README for more info about this).
- It is jumping when you click on the title. But where is it jumping to? it is going to `timeline.md` as that is the note with the info as you can see from the html code in your note where it says `<a class="internal-link" href="timeline.md">TITLE</a>`. 
- Copy the stuff you have in your second image (i.e. timeline note) into your Repository.md note and then go anywhere and write `test` then insert the timeline and it should work. 

The way the plugin works:
- it reads the list of tags that you select `test;me` for example
- It searches for ALL NOTES that have `YAML tags` (not just in-line tags like you have in your Repository.md now): timeline + test + me (if it doesn't have all these in the YAML the note is ignored
- It searches for each note that passed the previous filter if it has an `info block` meaning the <span class="ob-timeline"> section. If the note doesn't have this it is ignored. 

in your case Repository doesn't have the YAML tags and is ignored while timeline note has all the needed criteria and is shown. 

### **_Duration Events:_**
----
The problem is not presenting the duration events with a spanning section. This is possible and I had it in the early version. However, the problem with these is the stacking behavior where in many cases (especially with long and detailed timelines) there will be too much to stack next to each other and it will overflow and make the timeline ugly. 

What can possibly be a solution is to allow clicking a `card` and if it has a duration it will be shown, that way it is user controlled (yet this is fails to provide a generated view for the user to explore beforehand).

However, before this I want to replace the html code with a render block to keep the note clean and allow to easily replace a timeline (once i have some free time to do so that is)

**Comment by emory** [comment]
>     * There is no note having **_ALL of the tags searched_** for in the **_YAML_** (its important to note that the tags must be in the YAML and not simple normal tag within the note (they are recorded separately by obsidian)). This below must be in at least 1 note.

> @emory Can you please post an example note if the above doesn't help.

I've been using jekyll for years and I add tags to my frontmatter like this:

```
---
title: "testing timeline"
type: [ zettel, worklog ]
date: 2021-02-26
id: 20210226163103
tags: [ "#timeline", "#testing" ]
---
```

My daily notes in my vaults always have at least these tags:

```
tags: [ "#daily", "#diary" ]
```

Quoting things in my yaml frontmatter is how I avoid jekyll barfing all over the place because I have a contraction in my `title:` or something else objectionable.

**Comment by Darakah** [comment]
@emory 

can you please replace `[ "#timeline", "#testing" ]` with `[ "timeline", "testing" ]` and let me know what happens please?

**Comment by emory** [comment]
Nothing different seems to happen. Document says: 

```
---
title: "testing timeline"
type: [ zettel, worklog ]
date: 2021-02-26
id: 20210226163103
tags: [ "timeline", "testing" ]
---

My daily notes in my vaults always have at least these tags:

timeline;test

And I'll select that and use the cmd-p > create timeline command!
```

I do that and: ( …skipping frontmatter):

```
My daily notes in my vaults always have at least these tags:

<div class="timeline"></div>

And I'll select that and use the cmd-p > create timeline command!
```

I'm looking around to see if Obsidian is logging an error or anything somewhere. Not seeing any errors in Console and ~/Library/Logs isn't where they'd get dropped off apparently.

**Comment by emory** [comment]
@Darakah do you want me to split this into a separate issue, i don't mean to shit up a closed one for you, sorry about that.

**Comment by Darakah** [comment]
@emory No worries, 

yes, would be better to create a separate issue to figure this out.
Open in issue and if possible provide the following:
- Image of your current settings tab for the `Timelines` plugin
- Upload the MD note that you are using

Questions:
- Are you on the Obsidian discord server? Faster to figure this out. 
- In the above example you sent last you are writing `timeline;test` but the tags are `timeline;testing`. Is this just an error while you were writing the post or this is the actual note?

PS: after you create the separate issue, will clean this thread if that is ok.

**Comment by raquellewei** [comment]
can't find create timeline with cmd + P, even though the Timelines plugin is turned on
